build:
  environment:
    php: 8.4
  dependencies:
    before:
      - cp composer.json.dist composer.json
      - composer install --no-interaction --prefer-dist
  nodes:
    analysis:
      tests:
        override:
          - php-scrutinizer-run

filter:
  excluded_paths:
    - 'tests/'
    - 'extras/'
    - 'console/'
    - 'upgrade/'
    - 'docs/'
  dependency_paths:
    - 'xoops_lib/vendor/'

tools:
  php_analyzer: true
